import '../../shared/base.css'
import './style.css'

const base = import.meta.env.BASE_URL

document.querySelector('#app').innerHTML = `
  <header class="app-header">
    <div class="container header-inner">
      <a href="${base}ta-rail/" class="brand">
        <img src="${base}images/ta-rail/launch-icon.png" alt="TA Rail" class="brand-icon" />
        <span class="brand-name">TA Rail&trade;</span>
      </a>
    </div>
  </header>

  <main class="terms-content">
    <h1>Terms of Use</h1>
    <p class="last-updated">Effective Date: 6 May 2026 &nbsp;|&nbsp; Last Updated: 6 May 2026</p>
    <p class="intro">These Terms of Use ("Terms") govern your access to and use of the TA Rail mobile application ("Application" or "App") developed and operated by 29 Tech ("we", "us", or "our"). By downloading, installing, or using the Application, you ("User" or "you") agree to be bound by these Terms. If you do not agree, please do not use the Application.</p>

    <h2>1. License</h2>
    <p>We grant you a limited, non-exclusive, non-transferable, revocable license to use the Application on devices that you own or control, solely for your personal, non-commercial purposes and in accordance with these Terms.</p>
    <p>This license does not allow you to:</p>
    <ul>
      <li>Distribute or make the Application available over a network where it could be used by multiple devices at the same time</li>
      <li>Transfer, sublicense, lease, lend, or rent the Application to any third party</li>
      <li>Copy, reverse-engineer, disassemble, decompile, decode, adapt, or attempt to derive the source code of the Application (except to the extent applicable law expressly permits)</li>
      <li>Modify or create derivative works based on the Application</li>
      <li>Remove, alter, or obscure any copyright, trademark, or other proprietary notices in the Application</li>
    </ul>

    <h2>2. Subscriptions and Payments</h2>
    <p>Certain features of the Application require a paid subscription. All payments are processed through the Google Play Store (Google LLC) and/or Apple App Store (Apple Inc.). We do not directly collect or store your payment information.</p>
    <p>Subscription terms, pricing, renewal, and cancellation are governed by the policies of the respective app store through which you purchased the subscription. Please refer to the Google Play or Apple App Store terms for details.</p>

    <h2>3. User Content and Data</h2>
    <p>You are solely responsible for the accuracy and legality of any data or content you enter into the Application, including your profile information, duty entries, and travel details.</p>
    <p>We may collect and use technical data and related information — including but not limited to application version, platform type, and usage logs — to facilitate software updates, product support, and service improvements. Such data is used in a form that does not personally identify you. For full details, please refer to our <a href="${base}ta-rail/privacy-policy/">Privacy Policy</a>.</p>

    <h2>4. Third-Party Services</h2>
    <p>The Application may integrate with or enable access to third-party services (such as Firebase, RevenueCat, Google Play, and Apple App Store). Your use of such services is at your own risk and subject to the respective third party's terms and privacy policies.</p>
    <p>We are not responsible for the content, accuracy, availability, or reliability of any third-party services. We reserve the right to change, suspend, or remove access to any third-party service at any time without notice.</p>

    <h2>5. Acceptable Use</h2>
    <p>You agree not to use the Application to:</p>
    <ul>
      <li>Violate any applicable law, regulation, or government order</li>
      <li>Infringe the intellectual property rights of 29 Tech or any third party</li>
      <li>Harass, abuse, stalk, threaten, or defame any person or entity</li>
      <li>Transmit malware, viruses, or any other harmful code</li>
      <li>Interfere with or disrupt the Application's functionality or servers</li>
    </ul>

    <h2>6. Disclaimer</h2>
    <p>The TA Rail Application is an independent tool for assisting with travelling allowance calculations based on the Indian Railway Establishment Code. It is not affiliated with, endorsed by, or connected to the Indian Railways, the Ministry of Railways, or the Government of India.</p>
    <p class="caps-block">TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE APPLICATION AND ALL SERVICES PROVIDED THROUGH IT ARE OFFERED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, AND NON-INFRINGEMENT.</p>
    <p>While we strive to ensure accuracy, the calculations, data, and outputs generated by the Application are intended as an assistive tool and may vary based on individual circumstances. Users are advised to verify all results before official use or submission.</p>

    <h2>7. Limitation of Liability</h2>
    <p class="caps-block">TO THE EXTENT PERMITTED BY LAW, IN NO EVENT SHALL 29 TECH BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF DATA, LOSS OF PROFITS, OR BUSINESS INTERRUPTION, ARISING OUT OF OR RELATED TO YOUR USE OF OR INABILITY TO USE THE APPLICATION, HOWEVER CAUSED AND REGARDLESS OF THE THEORY OF LIABILITY.</p>
    <p>In no event shall our total liability to you for all claims arising from or related to the Application exceed the amount you paid to us (if any) in the twelve (12) months preceding the claim, or five hundred Indian Rupees (&rupee;500), whichever is greater.</p>

    <h2>8. Termination</h2>
    <p>These Terms are effective until terminated. We may suspend or terminate your access to the Application at any time, without prior notice, if you breach any provision of these Terms.</p>
    <p>Upon termination, your license to use the Application ceases immediately. You may terminate these Terms at any time by uninstalling the Application and deleting your account.</p>

    <h2>9. Changes to These Terms</h2>
    <p>We may update these Terms from time to time. Changes will be posted within the Application or on this page. Your continued use of the Application after changes are posted constitutes your acceptance of the updated Terms.</p>

    <h2>10. Governing Law</h2>
    <p>These Terms shall be governed by and construed in accordance with the laws of the Republic of India. Any disputes arising from these Terms or your use of the Application shall be subject to the exclusive jurisdiction of the courts in Madhya Pradesh, India.</p>

    <h2>11. Platform Providers</h2>
    <p>The Application may be distributed through third-party platforms, including the Google Play Store (Google LLC) and the Apple App Store (Apple Inc.) (collectively, &ldquo;Platform Providers&rdquo;). You acknowledge and agree that:</p>
    <ul>
      <li>These Terms are between you and 29 Tech only, and not with any Platform Provider. Platform Providers are not responsible for the Application or its content.</li>
      <li>Platform Providers have no obligation to furnish any maintenance or support services with respect to the Application.</li>
      <li>Platform Providers are not responsible for addressing any claims by you or any third party relating to the Application, including product liability claims, consumer protection claims, intellectual property claims, or any claim that the Application fails to conform to any applicable legal or regulatory requirement.</li>
      <li>In the event of any failure of the Application to conform to any applicable warranty, you may notify the relevant Platform Provider, who may refund the purchase price (if any) of the Application. To the maximum extent permitted by applicable law, Platform Providers have no other warranty obligation with respect to the Application.</li>
      <li>Platform Providers are third-party beneficiaries of these Terms and, upon your acceptance, have the right to enforce these Terms against you.</li>
    </ul>

    <h2>12. Contact Us</h2>
    <p>If you have questions or concerns about these Terms of Use, please contact us:</p>
    <div class="contact-block">
      <p><strong>29 Tech</strong></p>
      <p><strong>Email:</strong> <a href="mailto:harshupbishnoi@gmail.com">harshupbishnoi@gmail.com</a></p>
    </div>
  </main>

  <footer class="app-footer">
    <div class="container">
      <div class="footer-top">
        <div class="footer-brand-col">
          <div class="footer-brand">
            <img src="${base}images/ta-rail/launch-icon.png" alt="" class="footer-icon" />
            <span>TA Rail&trade;</span>
          </div>
          <p class="footer-brand-desc">Travelling allowance calculation app based on Indian Railway Establishment Code.</p>
        </div>
        <div class="footer-col">
          <h4>Download</h4>
          <ul>
            <li><a href="#">Android (Google Play)</a></li>
            <li><a href="#">iOS (App Store)</a></li>
          </ul>
        </div>
        <div class="footer-col">
          <h4>Legal</h4>
          <ul>
            <li><a href="${base}ta-rail/privacy-policy/">Privacy Policy</a></li>
            <li><a href="${base}ta-rail/terms-of-use/">Terms of Use</a></li>
          </ul>
        </div>
        <div class="footer-col">
          <h4>Support</h4>
          <ul>
            <li><a href="mailto:contact@29tech.co.in">contact@29tech.co.in</a></li>
          </ul>
        </div>
      </div>
      <div class="footer-bottom">
        <span>&copy; ${new Date().getFullYear()} 29 Tech&trade;. All rights reserved.</span>
        <a href="${base}ta-rail/">Back to TA Rail&trade;</a>
      </div>
    </div>
  </footer>
`
